[build-system]
requires = ["setuptools>=45", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "dashboard"
version = "0.1.0"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "config*"]
